//
// DO NOT EDIT THIS FILE
// This file was generated using Pokabbie\CustomJson from 'src/data/rogue/custom_mons.json'
//

#define TRAINER_ID_CLOWN (OTID_FLAG_CUSTOM_MON | 24401)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_CLOWN[PLAYER_NAME_LENGTH + 1] = _("Clown");
#else
static u8 const sTrainerName_CLOWN[PLAYER_NAME_LENGTH + 1] = _("CLOWN");
#endif
#define TRAINER_ID_RED (OTID_FLAG_CUSTOM_MON | 48211)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_RED[PLAYER_NAME_LENGTH + 1] = _("Red");
#else
static u8 const sTrainerName_RED[PLAYER_NAME_LENGTH + 1] = _("RED");
#endif
#define TRAINER_ID_WAHEY (OTID_FLAG_CUSTOM_MON | 22822)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_WAHEY[PLAYER_NAME_LENGTH + 1] = _("Wahey");
#else
static u8 const sTrainerName_WAHEY[PLAYER_NAME_LENGTH + 1] = _("WAHEY");
#endif
#define TRAINER_ID_QUESTS (OTID_FLAG_CUSTOM_MON | 63294)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_QUESTS[PLAYER_NAME_LENGTH + 1] = _("Quests");
#else
static u8 const sTrainerName_QUESTS[PLAYER_NAME_LENGTH + 1] = _("QUESTS");
#endif
#define TRAINER_ID_QMARKQMARKQMARKQMARKQMARK (OTID_FLAG_CUSTOM_MON | 181)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_QMARKQMARKQMARKQMARKQMARK[PLAYER_NAME_LENGTH + 1] = _("?????");
#else
static u8 const sTrainerName_QMARKQMARKQMARKQMARKQMARK[PLAYER_NAME_LENGTH + 1] = _("?????");
#endif
#define TRAINER_ID_ABBIE (OTID_FLAG_CUSTOM_MON | 181)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_ABBIE[PLAYER_NAME_LENGTH + 1] = _("Abbie");
#else
static u8 const sTrainerName_ABBIE[PLAYER_NAME_LENGTH + 1] = _("ABBIE");
#endif
#define TRAINER_ID_COMMON (OTID_FLAG_CUSTOM_MON | 43742)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_COMMON[PLAYER_NAME_LENGTH + 1] = _("Common");
#else
static u8 const sTrainerName_COMMON[PLAYER_NAME_LENGTH + 1] = _("COMMON");
#endif
#define TRAINER_ID_RARE (OTID_FLAG_CUSTOM_MON | 47687)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_RARE[PLAYER_NAME_LENGTH + 1] = _("Rare");
#else
static u8 const sTrainerName_RARE[PLAYER_NAME_LENGTH + 1] = _("RARE");
#endif
#define TRAINER_ID_EPIC (OTID_FLAG_CUSTOM_MON | 41438)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_EPIC[PLAYER_NAME_LENGTH + 1] = _("Epic");
#else
static u8 const sTrainerName_EPIC[PLAYER_NAME_LENGTH + 1] = _("EPIC");
#endif
#define TRAINER_ID_EXOTIC (OTID_FLAG_CUSTOM_MON | 42241)
#ifdef ROGUE_EXPANSION
static u8 const sTrainerName_EXOTIC[PLAYER_NAME_LENGTH + 1] = _("Exotic");
#else
static u8 const sTrainerName_EXOTIC[PLAYER_NAME_LENGTH + 1] = _("EXOTIC");
#endif

#ifdef ROGUE_EXPANSION
static u8 const sMonNickname_CLOWN_STANTLER[] = _("Kurt");
#else
static u8 const sMonNickname_CLOWN_STANTLER[] = _("KURT");
#endif
#if !defined(ROGUE_EXPANSION)
#ifdef ROGUE_EXPANSION
static u8 const sMonNickname_ABBIE_MAREEP[] = _("Pikin");
#else
static u8 const sMonNickname_ABBIE_MAREEP[] = _("PIKIN");
#endif
static u16 const sMonMoves_ABBIE_MAREEP[] = {
    MOVE_DRAGON_BREATH,
    MOVE_MAGIC_COAT,
    MOVE_THUNDER,
    MOVE_TAIL_GLOW,
    MOVE_BLIZZARD,
};
#endif
#if defined(ROGUE_EXPANSION)
#ifdef ROGUE_EXPANSION
static u8 const sMonNickname_ABBIE_MAREEP[] = _("Pikin");
#else
static u8 const sMonNickname_ABBIE_MAREEP[] = _("PIKIN");
#endif
static u16 const sMonMoves_ABBIE_MAREEP[] = {
    MOVE_METEOR_BEAM,
    MOVE_SPLISHY_SPLASH,
    MOVE_THUNDERCLAP,
    MOVE_TAIL_GLOW,
    MOVE_HURRICANE,
};
static u16 const sMonAbilities_ABBIE_MAREEP[NUM_ABILITY_SLOTS] = {
    ABILITY_FLUFFY,
    ABILITY_NONE,
    ABILITY_TERAVOLT,
};
#endif
static u16 const sMonMoves_WAHEY_ELECTRODE[] = {
    MOVE_EXPLOSION,
    MOVE_EXPLOSION,
    MOVE_EXPLOSION,
    MOVE_EXPLOSION,
};
static u16 const sMonAbilities_WAHEY_ELECTRODE[NUM_ABILITY_SLOTS] = {
    ABILITY_WONDER_GUARD,
};
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_FARFETCHD[] = {
    MOVE_ROCK_SLIDE,
    MOVE_EXTREME_SPEED,
    MOVE_DRILL_PECK,
    MOVE_SHARPEN,
};
static u16 const sMonAbilities_EXOTIC_FARFETCHD[NUM_ABILITY_SLOTS] = {
    ABILITY_HUGE_POWER,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_FARFETCHD[] = {
    MOVE_SACRED_SWORD,
    MOVE_CEASELESS_EDGE,
    MOVE_SOLAR_BLADE,
    MOVE_BITTER_BLADE,
};
static u16 const sMonAbilities_EXOTIC_FARFETCHD[NUM_ABILITY_SLOTS] = {
    ABILITY_SHARPNESS,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_SPINARAK[] = {
    MOVE_CRUNCH,
    MOVE_SWALLOW,
    MOVE_STOCKPILE,
    MOVE_SPIT_UP,
};
static u16 const sMonAbilities_EXOTIC_SPINARAK[NUM_ABILITY_SLOTS] = {
    ABILITY_BATTLE_ARMOR,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_SPINARAK[] = {
    MOVE_U_TURN,
    MOVE_GUNK_SHOT,
    MOVE_FELL_STINGER,
    MOVE_FIRST_IMPRESSION,
};
static u16 const sMonAbilities_EXOTIC_SPINARAK[NUM_ABILITY_SLOTS] = {
    ABILITY_ADAPTABILITY,
    ABILITY_BATTLE_ARMOR,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CASTFORM[] = {
    MOVE_FLY,
    MOVE_WISH,
    MOVE_SURF,
    MOVE_ERUPTION,
};
static u16 const sMonAbilities_EXOTIC_CASTFORM[NUM_ABILITY_SLOTS] = {
    ABILITY_FORECAST,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CASTFORM[] = {
    MOVE_SHORE_UP,
    MOVE_BLEAKWIND_STORM,
    MOVE_WILDBOLT_STORM,
    MOVE_SANDSEAR_STORM,
};
static u16 const sMonAbilities_EXOTIC_CASTFORM[NUM_ABILITY_SLOTS] = {
    ABILITY_FORECAST_PRIORITY,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_LOTAD[] = {
    MOVE_PETAL_DANCE,
    MOVE_FEATHER_DANCE,
    MOVE_SWORDS_DANCE,
    MOVE_DRAGON_DANCE,
};
static u16 const sMonAbilities_EXOTIC_LOTAD[NUM_ABILITY_SLOTS] = {
    ABILITY_GUTS,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_LOTAD[] = {
    MOVE_PETAL_DANCE,
    MOVE_QUIVER_DANCE,
    MOVE_FEATHER_DANCE,
    MOVE_LUNAR_DANCE,
};
static u16 const sMonAbilities_EXOTIC_LOTAD[NUM_ABILITY_SLOTS] = {
    ABILITY_DANCER,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CARNIVINE[] = {
    MOVE_TROP_KICK,
    MOVE_AIR_SLASH,
    MOVE_MALIGNANT_CHAIN,
    MOVE_SPORE,
};
static u16 const sMonAbilities_EXOTIC_CARNIVINE[NUM_ABILITY_SLOTS] = {
    ABILITY_UNBURDEN,
    ABILITY_SERENE_GRACE,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_KLINK[] = {
    MOVE_RAPID_SPIN,
    MOVE_BODY_PRESS,
    MOVE_BULK_UP,
    MOVE_ZIPPY_ZAP,
};
static u16 const sMonAbilities_EXOTIC_KLINK[NUM_ABILITY_SLOTS] = {
    ABILITY_LEVITATE,
    ABILITY_VOLT_ABSORB,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_LITLEO[] = {
    MOVE_FIERY_WRATH,
    MOVE_AURA_SPHERE,
    MOVE_BURNING_JEALOUSY,
    MOVE_BURNING_BULWARK,
};
static u16 const sMonAbilities_EXOTIC_LITLEO[NUM_ABILITY_SLOTS] = {
    ABILITY_FLASH_FIRE,
    ABILITY_INTIMIDATE,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_DRAMPA[] = {
    MOVE_SLUDGE_BOMB,
    MOVE_PSYCHIC,
    MOVE_FICKLE_BEAM,
    MOVE_BRINE,
};
static u16 const sMonAbilities_EXOTIC_DRAMPA[NUM_ABILITY_SLOTS] = {
    ABILITY_FLUFFY,
    ABILITY_STAMINA,
    ABILITY_NONE,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CLOBBOPUS[] = {
    MOVE_JET_PUNCH,
    MOVE_FLIP_TURN,
    MOVE_SWORDS_DANCE,
    MOVE_FLYING_PRESS,
};
static u16 const sMonAbilities_EXOTIC_CLOBBOPUS[NUM_ABILITY_SLOTS] = {
    ABILITY_WATER_VEIL,
    ABILITY_SWIFT_SWIM,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CAPSAKID[] = {
    MOVE_SEED_FLARE,
    MOVE_MAGMA_STORM,
    MOVE_QUIVER_DANCE,
    MOVE_BURN_UP,
};
static u16 const sMonAbilities_EXOTIC_CAPSAKID[NUM_ABILITY_SLOTS] = {
    ABILITY_SEED_SOWER,
    ABILITY_ANGER_SHELL,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_PIKACHU[] = {
    MOVE_FLY,
    MOVE_EXTREME_SPEED,
    MOVE_CALM_MIND,
    MOVE_ICY_WIND,
};
static u16 const sMonAbilities_EXOTIC_PIKACHU[NUM_ABILITY_SLOTS] = {
    ABILITY_VOLT_ABSORB,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_PIKACHU_ORIGINAL_CAP[] = {
    MOVE_FLY,
    MOVE_FLIP_TURN,
    MOVE_EXTREME_SPEED,
    MOVE_MOONBLAST,
};
static u16 const sMonAbilities_EXOTIC_PIKACHU_ORIGINAL_CAP[NUM_ABILITY_SLOTS] = {
    ABILITY_PROTEAN,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_WAHEY_WOBBUFFET[] = {
    MOVE_FIRE_PUNCH,
    MOVE_ICE_PUNCH,
    MOVE_MACH_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_SHADOW_PUNCH,
    MOVE_COMET_PUNCH,
    MOVE_DYNAMIC_PUNCH,
    MOVE_MEGA_PUNCH,
};
static u16 const sMonAbilities_WAHEY_WOBBUFFET[NUM_ABILITY_SLOTS] = {
    ABILITY_HUGE_POWER,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_WAHEY_WOBBUFFET[] = {
    MOVE_DRAIN_PUNCH,
    MOVE_KINGS_SHIELD,
    MOVE_POWER_UP_PUNCH,
    MOVE_SHADOW_PUNCH,
    MOVE_BULLET_PUNCH,
    MOVE_COMET_PUNCH,
    MOVE_DYNAMIC_PUNCH,
    MOVE_MACH_PUNCH,
    MOVE_MEGA_PUNCH,
    MOVE_SUCKER_PUNCH,
};
static u16 const sMonAbilities_WAHEY_WOBBUFFET[NUM_ABILITY_SLOTS] = {
    ABILITY_STANCE_CHANGE,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CHIMECHO[] = {
    MOVE_WATER_SPOUT,
    MOVE_ERUPTION,
    MOVE_METRONOME,
    MOVE_CRUNCH,
};
static u16 const sMonAbilities_EXOTIC_CHIMECHO[NUM_ABILITY_SLOTS] = {
    ABILITY_COLOR_CHANGE,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_TYMPOLE[] = {
    MOVE_FIRE_PUNCH,
    MOVE_THUNDER_PUNCH,
    MOVE_BULLET_PUNCH,
    MOVE_SURGING_STRIKES,
};
static u16 const sMonAbilities_EXOTIC_TYMPOLE[NUM_ABILITY_SLOTS] = {
    ABILITY_MOODY,
    ABILITY_IRON_FIST,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_ARON[] = {
    MOVE_METEOR_MASH,
    MOVE_SWORDS_DANCE,
    MOVE_SUPERPOWER,
    MOVE_FIRE_BLAST,
};
static u16 const sMonAbilities_EXOTIC_ARON[NUM_ABILITY_SLOTS] = {
    ABILITY_SAND_STREAM,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_BURMY[] = {
    MOVE_TAIL_GLOW,
    MOVE_SEED_FLARE,
    MOVE_EARTH_POWER,
    MOVE_SPRINGTIDE_STORM,
};
static u16 const sMonAbilities_EXOTIC_BURMY[NUM_ABILITY_SLOTS] = {
    ABILITY_GRASSY_SURGE,
    ABILITY_BEADS_OF_RUIN,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_MISDREAVUS[] = {
    MOVE_KNOCK_OFF,
    MOVE_LEECH_LIFE,
    MOVE_BUBBLE_BEAM,
    MOVE_POISON_FANG,
};
static u16 const sMonAbilities_EXOTIC_MISDREAVUS[NUM_ABILITY_SLOTS] = {
    ABILITY_LIGHTNING_ROD,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_CARBINK[] = {
    MOVE_LUNAR_BLESSING,
    MOVE_HYPER_DRILL,
    MOVE_MORTAL_SPIN,
    MOVE_TIDY_UP,
};
static u16 const sMonAbilities_EXOTIC_CARBINK[NUM_ABILITY_SLOTS] = {
    ABILITY_PRISM_ARMOR,
    ABILITY_MIRROR_ARMOR,
    ABILITY_EARTH_EATER,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_HOOTHOOT[] = {
    MOVE_CALM_MIND,
    MOVE_HEAT_WAVE,
    MOVE_MOONLIGHT,
    MOVE_MUDDY_WATER,
};
static u16 const sMonAbilities_EXOTIC_HOOTHOOT[NUM_ABILITY_SLOTS] = {
    ABILITY_COMPOUND_EYES,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_WATTREL[] = {
    MOVE_AURA_SPHERE,
    MOVE_THUNDERCLAP,
    MOVE_OBLIVION_WING,
    MOVE_ELECTRO_SHOT,
};
static u16 const sMonAbilities_EXOTIC_WATTREL[NUM_ABILITY_SLOTS] = {
    ABILITY_STORM_DRAIN,
    ABILITY_LIGHTNING_ROD,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_AZURILL[] = {
    MOVE_TAIL_GLOW,
    MOVE_AGILITY,
    MOVE_SLACK_OFF,
    MOVE_CRUNCH,
};
static u16 const sMonAbilities_EXOTIC_AZURILL[NUM_ABILITY_SLOTS] = {
    ABILITY_SWIFT_SWIM,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_SHINX[] = {
    MOVE_HONE_CLAWS,
    MOVE_BLAZING_TORQUE,
    MOVE_HIGH_HORSEPOWER,
    MOVE_GUNK_SHOT,
};
static u16 const sMonAbilities_EXOTIC_SHINX[NUM_ABILITY_SLOTS] = {
    ABILITY_DEFIANT,
    ABILITY_MOXIE,
    ABILITY_ELECTROMORPHOSIS,
};
#endif
#if !defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_EKANS[] = {
    MOVE_ROLLOUT,
    MOVE_ICE_BALL,
    MOVE_DEFENSE_CURL,
    MOVE_MILK_DRINK,
};
static u16 const sMonAbilities_EXOTIC_EKANS[NUM_ABILITY_SLOTS] = {
    ABILITY_SPEED_BOOST,
};
#endif
#if defined(ROGUE_EXPANSION)
static u16 const sMonMoves_EXOTIC_VENIPEDE[] = {
    MOVE_MORTAL_SPIN,
    MOVE_POUNCE,
    MOVE_SUCKER_PUNCH,
    MOVE_MILK_DRINK,
};
static u16 const sMonAbilities_EXOTIC_VENIPEDE[NUM_ABILITY_SLOTS] = {
    ABILITY_TOXIC_DEBRIS,
    ABILITY_POISON_PUPPETEER,
    ABILITY_TECHNICIAN,
};
#endif

static struct CustomTrainerData const sCustomTrainers[] = 
{
    [CUSTOM_TRAINER_NONE] = {},
    [CUSTOM_TRAINER_CLOWN]
    {
        .name = sTrainerName_CLOWN,
        .trainerId = TRAINER_ID_CLOWN,
        .trainerColour = 0,
    },
    [CUSTOM_TRAINER_RED]
    {
        .name = sTrainerName_RED,
        .trainerId = TRAINER_ID_RED,
        .trainerColour = 0,
    },
    [CUSTOM_TRAINER_WAHEY]
    {
        .name = sTrainerName_WAHEY,
        .trainerId = TRAINER_ID_WAHEY,
        .trainerColour = 0,
    },
    [CUSTOM_TRAINER_QUESTS]
    {
        .name = sTrainerName_QUESTS,
        .trainerId = TRAINER_ID_QUESTS,
        .trainerColour = 0,
    },
    [CUSTOM_TRAINER_QMARKQMARKQMARKQMARKQMARK]
    {
        .name = sTrainerName_QMARKQMARKQMARKQMARKQMARK,
        .trainerId = TRAINER_ID_QMARKQMARKQMARKQMARKQMARK,
        .trainerColour = 1,
    },
    [CUSTOM_TRAINER_ABBIE]
    {
        .name = sTrainerName_ABBIE,
        .trainerId = TRAINER_ID_ABBIE,
        .trainerColour = 1,
    },
    [CUSTOM_TRAINER_COMMON]
    {
        .name = sTrainerName_COMMON,
        .trainerId = TRAINER_ID_COMMON,
        .trainerColour = 0,
    },
    [CUSTOM_TRAINER_RARE]
    {
        .name = sTrainerName_RARE,
        .trainerId = TRAINER_ID_RARE,
        .trainerColour = 0,
    },
    [CUSTOM_TRAINER_EPIC]
    {
        .name = sTrainerName_EPIC,
        .trainerId = TRAINER_ID_EPIC,
        .trainerColour = 1,
    },
    [CUSTOM_TRAINER_EXOTIC]
    {
        .name = sTrainerName_EXOTIC,
        .trainerId = TRAINER_ID_EXOTIC,
        .trainerColour = 1,
    },
};

static struct CustomMonData const sCustomPokemon[] = 
{
    [CUSTOM_MON_NONE] = {},
    [CUSTOM_MON_CLOWN_STANTLER]
    {
        .species = SPECIES_STANTLER,
        .pokeball = ITEM_CUSTOM_MON_POKEBALL,
        .isShiny = TRUE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_CLOWN,
        .otId = TRAINER_ID_CLOWN,
        .nickname = sMonNickname_CLOWN_STANTLER,
        .moves = NULL,
        .movesCount = 0,
        .abilities = NULL,
    },
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_ABBIE_MAREEP]
    {
        .species = SPECIES_MAREEP,
        .pokeball = ITEM_POKABBIE_POKEBALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_ABBIE,
        .otId = TRAINER_ID_ABBIE,
        .nickname = sMonNickname_ABBIE_MAREEP,
        .moves = sMonMoves_ABBIE_MAREEP,
        .movesCount = ARRAY_COUNT(sMonMoves_ABBIE_MAREEP),
        .abilities = NULL,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_ABBIE_MAREEP]
    {
        .species = SPECIES_MAREEP,
        .pokeball = ITEM_POKABBIE_POKEBALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_ABBIE,
        .otId = TRAINER_ID_ABBIE,
        .nickname = sMonNickname_ABBIE_MAREEP,
        .moves = sMonMoves_ABBIE_MAREEP,
        .movesCount = ARRAY_COUNT(sMonMoves_ABBIE_MAREEP),
        .abilities = sMonAbilities_ABBIE_MAREEP,
    },
#endif
    [CUSTOM_MON_WAHEY_ELECTRODE]
    {
        .species = SPECIES_ELECTRODE,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_SILK_SCARF,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_WAHEY,
        .otId = TRAINER_ID_WAHEY,
        .nickname = NULL,
        .moves = sMonMoves_WAHEY_ELECTRODE,
        .movesCount = ARRAY_COUNT(sMonMoves_WAHEY_ELECTRODE),
        .abilities = sMonAbilities_WAHEY_ELECTRODE,
    },
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_FARFETCHD]
    {
        .species = SPECIES_FARFETCHD,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_FARFETCHD,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_FARFETCHD),
        .abilities = sMonAbilities_EXOTIC_FARFETCHD,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_FARFETCHD]
    {
        .species = SPECIES_FARFETCHD,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_FARFETCHD,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_FARFETCHD),
        .abilities = sMonAbilities_EXOTIC_FARFETCHD,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_SPINARAK]
    {
        .species = SPECIES_SPINARAK,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_SPINARAK,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_SPINARAK),
        .abilities = sMonAbilities_EXOTIC_SPINARAK,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_SPINARAK]
    {
        .species = SPECIES_SPINARAK,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_SPINARAK,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_SPINARAK),
        .abilities = sMonAbilities_EXOTIC_SPINARAK,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CASTFORM]
    {
        .species = SPECIES_CASTFORM,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CASTFORM,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CASTFORM),
        .abilities = sMonAbilities_EXOTIC_CASTFORM,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CASTFORM]
    {
        .species = SPECIES_CASTFORM,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CASTFORM,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CASTFORM),
        .abilities = sMonAbilities_EXOTIC_CASTFORM,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_LOTAD]
    {
        .species = SPECIES_LOTAD,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_LOTAD,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_LOTAD),
        .abilities = sMonAbilities_EXOTIC_LOTAD,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_LOTAD]
    {
        .species = SPECIES_LOTAD,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_LOTAD,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_LOTAD),
        .abilities = sMonAbilities_EXOTIC_LOTAD,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CARNIVINE]
    {
        .species = SPECIES_CARNIVINE,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CARNIVINE,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CARNIVINE),
        .abilities = sMonAbilities_EXOTIC_CARNIVINE,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_KLINK]
    {
        .species = SPECIES_KLINK,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_KLINK,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_KLINK),
        .abilities = sMonAbilities_EXOTIC_KLINK,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_LITLEO]
    {
        .species = SPECIES_LITLEO,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_LITLEO,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_LITLEO),
        .abilities = sMonAbilities_EXOTIC_LITLEO,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_DRAMPA]
    {
        .species = SPECIES_DRAMPA,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_DRAMPA,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_DRAMPA),
        .abilities = sMonAbilities_EXOTIC_DRAMPA,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CLOBBOPUS]
    {
        .species = SPECIES_CLOBBOPUS,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CLOBBOPUS,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CLOBBOPUS),
        .abilities = sMonAbilities_EXOTIC_CLOBBOPUS,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CAPSAKID]
    {
        .species = SPECIES_CAPSAKID,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CAPSAKID,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CAPSAKID),
        .abilities = sMonAbilities_EXOTIC_CAPSAKID,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_PIKACHU]
    {
        .species = SPECIES_PIKACHU,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_PIKACHU,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_PIKACHU),
        .abilities = sMonAbilities_EXOTIC_PIKACHU,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_PIKACHU_ORIGINAL_CAP]
    {
        .species = SPECIES_PIKACHU_ORIGINAL_CAP,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_PIKACHU_ORIGINAL_CAP,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_PIKACHU_ORIGINAL_CAP),
        .abilities = sMonAbilities_EXOTIC_PIKACHU_ORIGINAL_CAP,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_WAHEY_WOBBUFFET]
    {
        .species = SPECIES_WOBBUFFET,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_LEFTOVERS,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_WAHEY,
        .otId = TRAINER_ID_WAHEY,
        .nickname = NULL,
        .moves = sMonMoves_WAHEY_WOBBUFFET,
        .movesCount = ARRAY_COUNT(sMonMoves_WAHEY_WOBBUFFET),
        .abilities = sMonAbilities_WAHEY_WOBBUFFET,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_WAHEY_WOBBUFFET]
    {
        .species = SPECIES_WOBBUFFET,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_KINGS_ROCK,
        .isDefaultSpawn = FALSE,
        .customTrainerId = CUSTOM_TRAINER_WAHEY,
        .otId = TRAINER_ID_WAHEY,
        .nickname = NULL,
        .moves = sMonMoves_WAHEY_WOBBUFFET,
        .movesCount = ARRAY_COUNT(sMonMoves_WAHEY_WOBBUFFET),
        .abilities = sMonAbilities_WAHEY_WOBBUFFET,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CHIMECHO]
    {
        .species = SPECIES_CHIMECHO,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CHIMECHO,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CHIMECHO),
        .abilities = sMonAbilities_EXOTIC_CHIMECHO,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_TYMPOLE]
    {
        .species = SPECIES_TYMPOLE,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_TYMPOLE,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_TYMPOLE),
        .abilities = sMonAbilities_EXOTIC_TYMPOLE,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_ARON]
    {
        .species = SPECIES_ARON,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_ARON,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_ARON),
        .abilities = sMonAbilities_EXOTIC_ARON,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_BURMY]
    {
        .species = SPECIES_BURMY,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_BURMY,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_BURMY),
        .abilities = sMonAbilities_EXOTIC_BURMY,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_MISDREAVUS]
    {
        .species = SPECIES_MISDREAVUS,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_MISDREAVUS,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_MISDREAVUS),
        .abilities = sMonAbilities_EXOTIC_MISDREAVUS,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_CARBINK]
    {
        .species = SPECIES_CARBINK,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_CARBINK,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_CARBINK),
        .abilities = sMonAbilities_EXOTIC_CARBINK,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_HOOTHOOT]
    {
        .species = SPECIES_HOOTHOOT,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_HOOTHOOT,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_HOOTHOOT),
        .abilities = sMonAbilities_EXOTIC_HOOTHOOT,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_WATTREL]
    {
        .species = SPECIES_WATTREL,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_WATTREL,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_WATTREL),
        .abilities = sMonAbilities_EXOTIC_WATTREL,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_AZURILL]
    {
        .species = SPECIES_AZURILL,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_AZURILL,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_AZURILL),
        .abilities = sMonAbilities_EXOTIC_AZURILL,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_SHINX]
    {
        .species = SPECIES_SHINX,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_SHINX,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_SHINX),
        .abilities = sMonAbilities_EXOTIC_SHINX,
    },
#endif
#if !defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_EKANS]
    {
        .species = SPECIES_EKANS,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_EKANS,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_EKANS),
        .abilities = sMonAbilities_EXOTIC_EKANS,
    },
#endif
#if defined(ROGUE_EXPANSION)
    [CUSTOM_MON_EXOTIC_VENIPEDE]
    {
        .species = SPECIES_VENIPEDE,
        .pokeball = ITEM_ROGUE_BALL,
        .isShiny = FALSE,
        .heldItem = ITEM_NONE,
        .isDefaultSpawn = TRUE,
        .customTrainerId = CUSTOM_TRAINER_EXOTIC,
        .otId = TRAINER_ID_EXOTIC,
        .nickname = NULL,
        .moves = sMonMoves_EXOTIC_VENIPEDE,
        .movesCount = ARRAY_COUNT(sMonMoves_EXOTIC_VENIPEDE),
        .abilities = sMonAbilities_EXOTIC_VENIPEDE,
    },
#endif
};

