//
// DO NOT EDIT THIS FILE
// This file was generated using Pokabbie\CustomJson from 'src/data/rogue/decorations.json'
//

static u8 const sText_GroupName_ENVIRONMENT[] = _("Environment");
static u16 const sText_Group_ENVIRONMENT[] =
{
    DECOR_ID_FLOWERS,
    DECOR_ID_GRASS_PATCHY,
    DECOR_ID_PATH,
    DECOR_ID_FLOWERS_PATCHY,
    DECOR_ID_CROPS,
    DECOR_ID_GRASS,
    DECOR_ID_MOUNTAIN,
    DECOR_ID_POND,
    DECOR_ID_TREE,
};

static u8 const sText_GroupName_MISC[] = _("Misc");
static u16 const sText_Group_MISC[] =
{
    DECOR_ID_REMOVE_DECOR,
};

static u8 const sText_GroupName_OBJECTS[] = _("Objects");
static u16 const sText_Group_OBJECTS[] =
{
    DECOR_ID_OUTFIT_CHANGING,
    DECOR_ID_PC,
    DECOR_ID_QUEST_BOARD,
    DECOR_ID_STATUE,
    DECOR_ID_BED,
    DECOR_ID_FLAG,
    DECOR_ID_PC_WANDERING_PKMN,
    DECOR_ID_APPLIANCES,
    DECOR_ID_CUSHIONS,
    DECOR_ID_DOLL,
};

static u8 const sText_GroupName_TILES_EXTERIOR[] = _("Tiles");
static u16 const sText_Group_TILES_EXTERIOR[] =
{
    DECOR_ID_BOULDER,
    DECOR_ID_BUSH,
    DECOR_ID_WOOD_SIGN,
    DECOR_ID_FANCY_SIGN,
    DECOR_ID_HORIZONTAL_FENCE,
    DECOR_ID_VERTICAL_FENCE,
};

static u8 const sText_GroupName_TILES_INTERIOR[] = _("Tiles");
static u16 const sText_Group_TILES_INTERIOR[] =
{
    DECOR_ID_RUG,
    DECOR_ID_CHAIR,
    DECOR_ID_DESK,
    DECOR_ID_PLANTS,
    DECOR_ID_FAUX_DOOR,
    DECOR_ID_MUDBALL,
    DECOR_ID_EFFECT_PADS,
    DECOR_ID_NOTE_PADS,
    DECOR_ID_WATER_BALLOON,
    DECOR_ID_CLIMBING_FRAME,
    DECOR_ID_SLIDE,
    DECOR_ID_SMALL_TV,
    DECOR_ID_TENT,
    DECOR_ID_LARGE_BRICK,
    DECOR_ID_LARGE_TIRE,
    DECOR_ID_SMALL_FENCE,
};

static struct RogueDecorationGroup const sDecorationGroups[DECOR_GROUP_COUNT] =
{
    [DECOR_GROUP_ENVIRONMENT] =
    {
        .name = sText_GroupName_ENVIRONMENT,
        .decorationIds = sText_Group_ENVIRONMENT,
        .decorationCount = ARRAY_COUNT(sText_Group_ENVIRONMENT),
    },
    [DECOR_GROUP_MISC] =
    {
        .name = sText_GroupName_MISC,
        .decorationIds = sText_Group_MISC,
        .decorationCount = ARRAY_COUNT(sText_Group_MISC),
    },
    [DECOR_GROUP_OBJECTS] =
    {
        .name = sText_GroupName_OBJECTS,
        .decorationIds = sText_Group_OBJECTS,
        .decorationCount = ARRAY_COUNT(sText_Group_OBJECTS),
    },
    [DECOR_GROUP_TILES_EXTERIOR] =
    {
        .name = sText_GroupName_TILES_EXTERIOR,
        .decorationIds = sText_Group_TILES_EXTERIOR,
        .decorationCount = ARRAY_COUNT(sText_Group_TILES_EXTERIOR),
    },
    [DECOR_GROUP_TILES_INTERIOR] =
    {
        .name = sText_GroupName_TILES_INTERIOR,
        .decorationIds = sText_Group_TILES_INTERIOR,
        .decorationCount = ARRAY_COUNT(sText_Group_TILES_INTERIOR),
    },
};

static u8 const sText_Str_0[] = _("Path");
static u8 const sText_Str_1[] = _("5x5");
static u8 const sText_Str_2[] = _("4x4");
static u8 const sText_Str_3[] = _("3x3");
static u8 const sText_Str_4[] = _("2x2");
static u8 const sText_Str_5[] = _("Grass");
static u8 const sText_Str_6[] = _("Grass Patchy");
static u8 const sText_Str_7[] = _("Flowers");
static u8 const sText_Str_8[] = _("Flowers Patchy");
static u8 const sText_Str_9[] = _("Crops");
static u8 const sText_Str_10[] = _("Mountain");
static u8 const sText_Str_11[] = _("Pond");
static u8 const sText_Str_12[] = _("Tree");
static u8 const sText_Str_13[] = _("1x1");
static u8 const sText_Str_14[] = _("Boulder");
static u8 const sText_Str_15[] = _("Default");
static u8 const sText_Str_16[] = _("Bush");
static u8 const sText_Str_17[] = _("Wood Sign");
static u8 const sText_Str_18[] = _("Fancy Sign");
static u8 const sText_Str_19[] = _("Horizontal Fence");
static u8 const sText_Str_20[] = _("5x1");
static u8 const sText_Str_21[] = _("4x1");
static u8 const sText_Str_22[] = _("3x1");
static u8 const sText_Str_23[] = _("2x1");
static u8 const sText_Str_24[] = _("Vertical Fence");
static u8 const sText_Str_25[] = _("Left 1x5");
static u8 const sText_Str_26[] = _("Left 1x4");
static u8 const sText_Str_27[] = _("Left 1x3");
static u8 const sText_Str_28[] = _("Left 1x2");
static u8 const sText_Str_29[] = _("Right 1x5");
static u8 const sText_Str_30[] = _("Right 1x4");
static u8 const sText_Str_31[] = _("Right 1x3");
static u8 const sText_Str_32[] = _("Right 1x2");
static u8 const sText_Str_33[] = _("Rug");
static u8 const sText_Str_34[] = _("Fire Blast");
static u8 const sText_Str_35[] = _("Fissure");
static u8 const sText_Str_36[] = _("Surf");
static u8 const sText_Str_37[] = _("Attract");
static u8 const sText_Str_38[] = _("Thunder");
static u8 const sText_Str_39[] = _("Powder Snow");
static u8 const sText_Str_40[] = _("Spikes");
static u8 const sText_Str_41[] = _("Chair");
static u8 const sText_Str_42[] = _("Brick");
static u8 const sText_Str_43[] = _("Bushy");
static u8 const sText_Str_44[] = _("Stone");
static u8 const sText_Str_45[] = _("Industrial");
static u8 const sText_Str_46[] = _("Wooden");
static u8 const sText_Str_47[] = _("Log");
static u8 const sText_Str_48[] = _("Pretty");
static u8 const sText_Str_49[] = _("Cute");
static u8 const sText_Str_50[] = _("Poké Ball");
static u8 const sText_Str_51[] = _("Desk");
static u8 const sText_Str_52[] = _("Small Wooden");
static u8 const sText_Str_53[] = _("Small Poké Ball");
static u8 const sText_Str_54[] = _("Medium Brick");
static u8 const sText_Str_55[] = _("Medium Bushy");
static u8 const sText_Str_56[] = _("Medium Stone");
static u8 const sText_Str_57[] = _("Medium Industrial");
static u8 const sText_Str_58[] = _("Medium Wooden");
static u8 const sText_Str_59[] = _("Medium Log");
static u8 const sText_Str_60[] = _("Large Brick");
static u8 const sText_Str_61[] = _("Large Bushy");
static u8 const sText_Str_62[] = _("Large Stone");
static u8 const sText_Str_63[] = _("Large Industrial");
static u8 const sText_Str_64[] = _("Large Wooden");
static u8 const sText_Str_65[] = _("Large Log");
static u8 const sText_Str_66[] = _("Plants");
static u8 const sText_Str_67[] = _("Red");
static u8 const sText_Str_68[] = _("Tropical");
static u8 const sText_Str_69[] = _("Colourful");
static u8 const sText_Str_70[] = _("Big");
static u8 const sText_Str_71[] = _("Gorgeous");
static u8 const sText_Str_72[] = _("Faux Door");
static u8 const sText_Str_73[] = _("MudBall");
static u8 const sText_Str_74[] = _("Note Pads");
static u8 const sText_Str_75[] = _("A");
static u8 const sText_Str_76[] = _("B");
static u8 const sText_Str_77[] = _("C");
static u8 const sText_Str_78[] = _("D");
static u8 const sText_Str_79[] = _("E");
static u8 const sText_Str_80[] = _("F");
static u8 const sText_Str_81[] = _("G");
static u8 const sText_Str_82[] = _("Effect Pads");
static u8 const sText_Str_83[] = _("Glitter");
static u8 const sText_Str_84[] = _("Jump");
static u8 const sText_Str_85[] = _("Spin");
static u8 const sText_Str_86[] = _("Water Balloon");
static u8 const sText_Str_87[] = _("Blue");
static u8 const sText_Str_88[] = _("Yellow");
static u8 const sText_Str_89[] = _("Climbing Frame");
static u8 const sText_Str_90[] = _("Slide");
static u8 const sText_Str_91[] = _("Tent");
static u8 const sText_Str_92[] = _("Small TV");
static u8 const sText_Str_93[] = _("Standard");
static u8 const sText_Str_94[] = _("Round");
static u8 const sText_Str_95[] = _("Large Tire");
static u8 const sText_Str_96[] = _("Small Fence");
static u8 const sText_Str_97[] = _("Horizontal");
static u8 const sText_Str_98[] = _("Vertical");
static u8 const sText_Str_99[] = _("Statue");
static u8 const sText_Str_100[] = _("Quest Board");
static u8 const sText_Str_101[] = _("PC");
static u8 const sText_Str_102[] = _("Bed");
static u8 const sText_Str_103[] = _("Outfit Changing");
static u8 const sText_Str_104[] = _("Wardrobe");
static u8 const sText_Str_105[] = _("Drawers");
static u8 const sText_Str_106[] = _("Flag");
static u8 const sText_Str_107[] = _("PC wandering {PKMN}");
static u8 const sText_Str_108[] = _("Appliances");
static u8 const sText_Str_109[] = _("Fan");
static u8 const sText_Str_110[] = _("Fridge");
static u8 const sText_Str_111[] = _("Microwave");
static u8 const sText_Str_112[] = _("Lawn Mower");
static u8 const sText_Str_113[] = _("Washing Machine");
static u8 const sText_Str_114[] = _("Cushions");
static u8 const sText_Str_115[] = _("Diamond");
static u8 const sText_Str_116[] = _("Fire");
static u8 const sText_Str_117[] = _("Kiss");
static u8 const sText_Str_118[] = _("Pikachu");
static u8 const sText_Str_119[] = _("Water");
static u8 const sText_Str_120[] = _("Zigzag");
static u8 const sText_Str_121[] = _("Doll");
static u8 const sText_Str_122[] = _("Azurill");
static u8 const sText_Str_123[] = _("Baltoy");
static u8 const sText_Str_124[] = _("Blastoise");
static u8 const sText_Str_125[] = _("Charizard");
static u8 const sText_Str_126[] = _("Lapras");
static u8 const sText_Str_127[] = _("Regice");
static u8 const sText_Str_128[] = _("Regirock");
static u8 const sText_Str_129[] = _("Registeel");
static u8 const sText_Str_130[] = _("Rhydon");
static u8 const sText_Str_131[] = _("Snorlax");
static u8 const sText_Str_132[] = _("Venusaur");
static u8 const sText_Str_133[] = _("Wailmer");
static u8 const sText_Str_134[] = _("Chikorita");
static u8 const sText_Str_135[] = _("Clefairy");
static u8 const sText_Str_136[] = _("Cyndaquil");
static u8 const sText_Str_137[] = _("Ditto");
static u8 const sText_Str_138[] = _("Duskull");
static u8 const sText_Str_139[] = _("Gulpin");
static u8 const sText_Str_140[] = _("Jigglypuff");
static u8 const sText_Str_141[] = _("Kecleon");
static u8 const sText_Str_142[] = _("Lotad");
static u8 const sText_Str_143[] = _("Magnemite");
static u8 const sText_Str_144[] = _("Marill");
static u8 const sText_Str_145[] = _("Meowth");
static u8 const sText_Str_146[] = _("Mudkip");
static u8 const sText_Str_147[] = _("Natu");
static u8 const sText_Str_148[] = _("Pichu");
static u8 const sText_Str_149[] = _("Porygon2");
static u8 const sText_Str_150[] = _("Seedot");
static u8 const sText_Str_151[] = _("Skitty");
static u8 const sText_Str_152[] = _("Smoochum");
static u8 const sText_Str_153[] = _("Squirtle");
static u8 const sText_Str_154[] = _("Swablu");
static u8 const sText_Str_155[] = _("Togepi");
static u8 const sText_Str_156[] = _("Torchic");
static u8 const sText_Str_157[] = _("Totodile");
static u8 const sText_Str_158[] = _("Treecko");
static u8 const sText_Str_159[] = _("Wooper");
static u8 const sText_Str_160[] = _("Wynaut");
static u8 const sText_Str_161[] = _("Remove Decor");

static struct RogueDecorationVariant const sDecorationVariants[DECOR_VARIANT_COUNT] =
{
    [DECOR_VARIANT_PATH_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_PATH_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_PATH_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_PATH_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_GRASS_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 25,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_GRASS_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 25,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_GRASS_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 25,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_GRASS_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 25,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_GRASS_PATCHY_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 30,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_GRASS_PATCHY_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 30,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_GRASS_PATCHY_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 30,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_GRASS_PATCHY_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 30,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_FLOWERS_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_FLOWERS_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_FLOWERS_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_FLOWERS_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_FLOWERS_PATCHY_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 20,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_FLOWERS_PATCHY_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 20,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_FLOWERS_PATCHY_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 20,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_FLOWERS_PATCHY_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 20,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_CROPS_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 35,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_CROPS_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 35,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_CROPS_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 35,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_CROPS_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 35,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_MOUNTAIN_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_MOUNTAIN,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_MOUNTAIN_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_MOUNTAIN,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_MOUNTAIN_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_MOUNTAIN,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_MOUNTAIN_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_MOUNTAIN,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_POND_5X5] =
    {
        .name = sText_Str_1,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 5,
            .width = 5,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_POND_4X4] =
    {
        .name = sText_Str_2,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 5,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_POND_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 5,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_POND_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_BACKGROUND,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 5,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_TREE_3X3] =
    {
        .name = sText_Str_3,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_SOLID_TILE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 10,
            .width = 6,
            .height = 6,
        } }
    },
    [DECOR_VARIANT_TREE_2X2] =
    {
        .name = sText_Str_4,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_SOLID_TILE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 10,
            .width = 4,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_TREE_1X1] =
    {
        .name = sText_Str_13,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_SOLID_TILE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 10,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_BOULDER_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 2,
            .y = 10,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_BUSH_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 10,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_WOOD_SIGN_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 10,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_FANCY_SIGN_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 1,
            .y = 10,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_HORIZONTAL_FENCE_5X1] =
    {
        .name = sText_Str_20,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 11,
            .width = 5,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_HORIZONTAL_FENCE_4X1] =
    {
        .name = sText_Str_21,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 11,
            .width = 4,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_HORIZONTAL_FENCE_3X1] =
    {
        .name = sText_Str_22,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 11,
            .width = 3,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_HORIZONTAL_FENCE_2X1] =
    {
        .name = sText_Str_23,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 11,
            .width = 2,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_LEFT_1X5] =
    {
        .name = sText_Str_25,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 10,
            .width = 1,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_LEFT_1X4] =
    {
        .name = sText_Str_26,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 10,
            .width = 1,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_LEFT_1X3] =
    {
        .name = sText_Str_27,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 7,
            .y = 10,
            .width = 1,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_LEFT_1X2] =
    {
        .name = sText_Str_28,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 8,
            .y = 10,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_RIGHT_1X5] =
    {
        .name = sText_Str_29,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 10,
            .width = 1,
            .height = 5,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_RIGHT_1X4] =
    {
        .name = sText_Str_30,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 11,
            .y = 10,
            .width = 1,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_RIGHT_1X3] =
    {
        .name = sText_Str_31,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 12,
            .y = 10,
            .width = 1,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_VERTICAL_FENCE_RIGHT_1X2] =
    {
        .name = sText_Str_32,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 13,
            .y = 10,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_RUG_FIRE_BLAST] =
    {
        .name = sText_Str_34,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_RUG_FISSURE] =
    {
        .name = sText_Str_35,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_RUG_SURF] =
    {
        .name = sText_Str_36,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_RUG_ATTRACT] =
    {
        .name = sText_Str_37,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 9,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_RUG_THUNDER] =
    {
        .name = sText_Str_38,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 12,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_RUG_POWDER_SNOW] =
    {
        .name = sText_Str_39,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_RUG_SPIKES] =
    {
        .name = sText_Str_40,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 18,
            .y = 9,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_CHAIR_BRICK] =
    {
        .name = sText_Str_42,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_BUSHY] =
    {
        .name = sText_Str_43,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 1,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_STONE] =
    {
        .name = sText_Str_44,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 2,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_INDUSTRIAL] =
    {
        .name = sText_Str_45,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_WOODEN] =
    {
        .name = sText_Str_46,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 4,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_LOG] =
    {
        .name = sText_Str_47,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_PRETTY] =
    {
        .name = sText_Str_48,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_CUTE] =
    {
        .name = sText_Str_49,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 7,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CHAIR_POKE_BALL] =
    {
        .name = sText_Str_50,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 8,
            .y = 8,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_DESK_SMALL_WOODEN] =
    {
        .name = sText_Str_52,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 2,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_DESK_SMALL_POKE_BALL] =
    {
        .name = sText_Str_53,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 3,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_DESK_MEDIUM_BRICK] =
    {
        .name = sText_Str_54,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 9,
            .y = 2,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_MEDIUM_BUSHY] =
    {
        .name = sText_Str_55,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 11,
            .y = 2,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_MEDIUM_STONE] =
    {
        .name = sText_Str_56,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 13,
            .y = 2,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_MEDIUM_INDUSTRIAL] =
    {
        .name = sText_Str_57,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 9,
            .y = 4,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_MEDIUM_WOODEN] =
    {
        .name = sText_Str_58,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 11,
            .y = 4,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_MEDIUM_LOG] =
    {
        .name = sText_Str_59,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 13,
            .y = 4,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_LARGE_BRICK] =
    {
        .name = sText_Str_60,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 2,
            .width = 3,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_LARGE_BUSHY] =
    {
        .name = sText_Str_61,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 2,
            .width = 3,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_LARGE_STONE] =
    {
        .name = sText_Str_62,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 2,
            .width = 3,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_LARGE_INDUSTRIAL] =
    {
        .name = sText_Str_63,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 4,
            .width = 3,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_LARGE_WOODEN] =
    {
        .name = sText_Str_64,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 4,
            .width = 3,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_DESK_LARGE_LOG] =
    {
        .name = sText_Str_65,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 4,
            .width = 3,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_PLANTS_RED] =
    {
        .name = sText_Str_67,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 6,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_PLANTS_TROPICAL] =
    {
        .name = sText_Str_68,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 4,
            .y = 6,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_PLANTS_PRETTY] =
    {
        .name = sText_Str_48,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 6,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_PLANTS_COLOURFUL] =
    {
        .name = sText_Str_69,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 6,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_PLANTS_BIG] =
    {
        .name = sText_Str_70,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 8,
            .y = 6,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_PLANTS_GORGEOUS] =
    {
        .name = sText_Str_71,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 6,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_FAUX_DOOR_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 5,
            .y = 0,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_MUDBALL_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 4,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_A] =
    {
        .name = sText_Str_75,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_B] =
    {
        .name = sText_Str_76,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 7,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_C] =
    {
        .name = sText_Str_77,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 8,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_D] =
    {
        .name = sText_Str_78,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 9,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_E] =
    {
        .name = sText_Str_79,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_F] =
    {
        .name = sText_Str_80,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 11,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_NOTE_PADS_G] =
    {
        .name = sText_Str_81,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 12,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_EFFECT_PADS_GLITTER] =
    {
        .name = sText_Str_83,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 9,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_EFFECT_PADS_JUMP] =
    {
        .name = sText_Str_84,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 10,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_EFFECT_PADS_SPIN] =
    {
        .name = sText_Str_85,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 11,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_WATER_BALLOON_RED] =
    {
        .name = sText_Str_67,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 6,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_WATER_BALLOON_BLUE] =
    {
        .name = sText_Str_87,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 7,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_WATER_BALLOON_YELLOW] =
    {
        .name = sText_Str_88,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 8,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_CLIMBING_FRAME_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 18,
            .y = 0,
            .width = 4,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_SLIDE_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 17,
            .y = 2,
            .width = 2,
            .height = 4,
        } }
    },
    [DECOR_VARIANT_TENT_RED] =
    {
        .name = sText_Str_67,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 12,
            .y = 6,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_TENT_BLUE] =
    {
        .name = sText_Str_87,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 6,
            .width = 3,
            .height = 3,
        } }
    },
    [DECOR_VARIANT_SMALL_TV_STANDARD] =
    {
        .name = sText_Str_93,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 13,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_SMALL_TV_ROUND] =
    {
        .name = sText_Str_94,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 14,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_SMALL_TV_CUTE] =
    {
        .name = sText_Str_49,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_LARGE_BRICK_RED] =
    {
        .name = sText_Str_67,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 1,
            .y = 0,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_LARGE_BRICK_BLUE] =
    {
        .name = sText_Str_87,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 2,
            .y = 0,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_LARGE_BRICK_YELLOW] =
    {
        .name = sText_Str_88,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 3,
            .y = 0,
            .width = 1,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_LARGE_TIRE_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_PLACEABLE_SURFACE,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 15,
            .y = 4,
            .width = 2,
            .height = 2,
        } }
    },
    [DECOR_VARIANT_SMALL_FENCE_HORIZONTAL] =
    {
        .name = sText_Str_97,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_SMALL_FENCE_VERTICAL] =
    {
        .name = sText_Str_98,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOME_INTERIOR),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOME_INTERIOR),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 1,
            .width = 1,
            .height = 1,
        } }
    },
    [DECOR_VARIANT_STATUE_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 1,
            .editorLocalId = 1,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_QUEST_BOARD_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 4,
            .editorLocalId = 4,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_PC_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 3,
            .editorLocalId = 3,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_BED_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 6,
            .editorLocalId = 6,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_OUTFIT_CHANGING_WARDROBE] =
    {
        .name = sText_Str_104,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 8,
            .editorLocalId = 8,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_OUTFIT_CHANGING_DRAWERS] =
    {
        .name = sText_Str_105,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 7,
            .editorLocalId = 7,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_FLAG_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 5,
            .editorLocalId = 5,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_PC_WANDERING_PKMN_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 14,
            .editorLocalId = 2,
            .capacityPerArea = 5,
        } }
    },
    [DECOR_VARIANT_APPLIANCES_FAN] =
    {
        .name = sText_Str_109,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 9,
            .editorLocalId = 9,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_APPLIANCES_FRIDGE] =
    {
        .name = sText_Str_110,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 10,
            .editorLocalId = 10,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_APPLIANCES_MICROWAVE] =
    {
        .name = sText_Str_111,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 11,
            .editorLocalId = 11,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_APPLIANCES_LAWN_MOWER] =
    {
        .name = sText_Str_112,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 12,
            .editorLocalId = 12,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_APPLIANCES_WASHING_MACHINE] =
    {
        .name = sText_Str_113,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 13,
            .editorLocalId = 13,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_POKE_BALL] =
    {
        .name = sText_Str_50,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 15,
            .editorLocalId = 15,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_DIAMOND] =
    {
        .name = sText_Str_115,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 16,
            .editorLocalId = 16,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_FIRE] =
    {
        .name = sText_Str_116,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 17,
            .editorLocalId = 17,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_GRASS] =
    {
        .name = sText_Str_5,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 18,
            .editorLocalId = 18,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_KISS] =
    {
        .name = sText_Str_117,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 19,
            .editorLocalId = 19,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_PIKACHU] =
    {
        .name = sText_Str_118,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 20,
            .editorLocalId = 20,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_ROUND] =
    {
        .name = sText_Str_94,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 21,
            .editorLocalId = 21,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_SPIN] =
    {
        .name = sText_Str_85,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 22,
            .editorLocalId = 22,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_WATER] =
    {
        .name = sText_Str_119,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 23,
            .editorLocalId = 23,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_CUSHIONS_ZIGZAG] =
    {
        .name = sText_Str_120,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 24,
            .editorLocalId = 24,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_AZURILL] =
    {
        .name = sText_Str_122,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 25,
            .editorLocalId = 25,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_BALTOY] =
    {
        .name = sText_Str_123,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 26,
            .editorLocalId = 26,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_BLASTOISE] =
    {
        .name = sText_Str_124,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 27,
            .editorLocalId = 27,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_CHARIZARD] =
    {
        .name = sText_Str_125,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 28,
            .editorLocalId = 28,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_LAPRAS] =
    {
        .name = sText_Str_126,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 29,
            .editorLocalId = 29,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_REGICE] =
    {
        .name = sText_Str_127,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 30,
            .editorLocalId = 30,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_REGIROCK] =
    {
        .name = sText_Str_128,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 31,
            .editorLocalId = 31,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_REGISTEEL] =
    {
        .name = sText_Str_129,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 32,
            .editorLocalId = 32,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_RHYDON] =
    {
        .name = sText_Str_130,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 33,
            .editorLocalId = 33,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_SNORLAX] =
    {
        .name = sText_Str_131,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 34,
            .editorLocalId = 34,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_VENUSAUR] =
    {
        .name = sText_Str_132,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 35,
            .editorLocalId = 35,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_WAILMER] =
    {
        .name = sText_Str_133,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 36,
            .editorLocalId = 36,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_CHIKORITA] =
    {
        .name = sText_Str_134,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 37,
            .editorLocalId = 37,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_CLEFAIRY] =
    {
        .name = sText_Str_135,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 38,
            .editorLocalId = 38,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_CYNDAQUIL] =
    {
        .name = sText_Str_136,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 39,
            .editorLocalId = 39,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_DITTO] =
    {
        .name = sText_Str_137,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 40,
            .editorLocalId = 40,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_DUSKULL] =
    {
        .name = sText_Str_138,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 41,
            .editorLocalId = 41,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_GULPIN] =
    {
        .name = sText_Str_139,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 42,
            .editorLocalId = 42,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_JIGGLYPUFF] =
    {
        .name = sText_Str_140,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 43,
            .editorLocalId = 43,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_KECLEON] =
    {
        .name = sText_Str_141,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 44,
            .editorLocalId = 44,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_LOTAD] =
    {
        .name = sText_Str_142,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 45,
            .editorLocalId = 45,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_MAGNEMITE] =
    {
        .name = sText_Str_143,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 59,
            .editorLocalId = 59,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_MARILL] =
    {
        .name = sText_Str_144,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 46,
            .editorLocalId = 46,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_MEOWTH] =
    {
        .name = sText_Str_145,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 47,
            .editorLocalId = 47,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_MUDKIP] =
    {
        .name = sText_Str_146,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 48,
            .editorLocalId = 48,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_NATU] =
    {
        .name = sText_Str_147,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 60,
            .editorLocalId = 60,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_PICHU] =
    {
        .name = sText_Str_148,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 49,
            .editorLocalId = 49,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_PIKACHU] =
    {
        .name = sText_Str_118,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 50,
            .editorLocalId = 50,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_PORYGON2] =
    {
        .name = sText_Str_149,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 61,
            .editorLocalId = 61,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_SEEDOT] =
    {
        .name = sText_Str_150,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 51,
            .editorLocalId = 51,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_SKITTY] =
    {
        .name = sText_Str_151,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 52,
            .editorLocalId = 52,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_SMOOCHUM] =
    {
        .name = sText_Str_152,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 53,
            .editorLocalId = 53,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_SQUIRTLE] =
    {
        .name = sText_Str_153,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 62,
            .editorLocalId = 62,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_SWABLU] =
    {
        .name = sText_Str_154,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 54,
            .editorLocalId = 54,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_TOGEPI] =
    {
        .name = sText_Str_155,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 55,
            .editorLocalId = 55,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_TORCHIC] =
    {
        .name = sText_Str_156,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 56,
            .editorLocalId = 56,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_TOTODILE] =
    {
        .name = sText_Str_157,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 57,
            .editorLocalId = 57,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_TREECKO] =
    {
        .name = sText_Str_158,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 58,
            .editorLocalId = 58,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_WOOPER] =
    {
        .name = sText_Str_159,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 63,
            .editorLocalId = 63,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_DOLL_WYNAUT] =
    {
        .name = sText_Str_160,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_OBJECTS,
        .type = DECOR_TYPE_OBJECT_EVENT,
        .perType = { .objectEvent =
        {
            .localId = 64,
            .editorLocalId = 64,
            .capacityPerArea = 0,
        } }
    },
    [DECOR_VARIANT_REMOVE_DECOR_DEFAULT] =
    {
        .name = sText_Str_15,
        .srcMapGroup = MAP_GROUP(ROGUE_TEMPLATE_HOMES),
        .srcMapNum = MAP_NUM(ROGUE_TEMPLATE_HOMES),
        .layer = DECOR_LAYER_DEFAULT,
        .type = DECOR_TYPE_TILE,
        .perType = { .tile =
        {
            .x = 0,
            .y = 0,
            .width = 1,
            .height = 1,
        } }
    },
};

static struct RogueDecoration const sDecorations[DECOR_ID_COUNT] =
{
    [DECOR_ID_PATH] =
    {
        .name = sText_Str_0,
        .firstVariantId = DECOR_VARIANT_PATH_5X5,
        .lastVariantId = DECOR_VARIANT_PATH_2X2,
    },
    [DECOR_ID_GRASS] =
    {
        .name = sText_Str_5,
        .firstVariantId = DECOR_VARIANT_GRASS_5X5,
        .lastVariantId = DECOR_VARIANT_GRASS_2X2,
    },
    [DECOR_ID_GRASS_PATCHY] =
    {
        .name = sText_Str_6,
        .firstVariantId = DECOR_VARIANT_GRASS_PATCHY_5X5,
        .lastVariantId = DECOR_VARIANT_GRASS_PATCHY_2X2,
    },
    [DECOR_ID_FLOWERS] =
    {
        .name = sText_Str_7,
        .firstVariantId = DECOR_VARIANT_FLOWERS_5X5,
        .lastVariantId = DECOR_VARIANT_FLOWERS_2X2,
    },
    [DECOR_ID_FLOWERS_PATCHY] =
    {
        .name = sText_Str_8,
        .firstVariantId = DECOR_VARIANT_FLOWERS_PATCHY_5X5,
        .lastVariantId = DECOR_VARIANT_FLOWERS_PATCHY_2X2,
    },
    [DECOR_ID_CROPS] =
    {
        .name = sText_Str_9,
        .firstVariantId = DECOR_VARIANT_CROPS_5X5,
        .lastVariantId = DECOR_VARIANT_CROPS_2X2,
    },
    [DECOR_ID_MOUNTAIN] =
    {
        .name = sText_Str_10,
        .firstVariantId = DECOR_VARIANT_MOUNTAIN_5X5,
        .lastVariantId = DECOR_VARIANT_MOUNTAIN_2X2,
    },
    [DECOR_ID_POND] =
    {
        .name = sText_Str_11,
        .firstVariantId = DECOR_VARIANT_POND_5X5,
        .lastVariantId = DECOR_VARIANT_POND_2X2,
    },
    [DECOR_ID_TREE] =
    {
        .name = sText_Str_12,
        .firstVariantId = DECOR_VARIANT_TREE_3X3,
        .lastVariantId = DECOR_VARIANT_TREE_1X1,
    },
    [DECOR_ID_BOULDER] =
    {
        .name = sText_Str_14,
        .firstVariantId = DECOR_VARIANT_BOULDER_DEFAULT,
        .lastVariantId = DECOR_VARIANT_BOULDER_DEFAULT,
    },
    [DECOR_ID_BUSH] =
    {
        .name = sText_Str_16,
        .firstVariantId = DECOR_VARIANT_BUSH_DEFAULT,
        .lastVariantId = DECOR_VARIANT_BUSH_DEFAULT,
    },
    [DECOR_ID_WOOD_SIGN] =
    {
        .name = sText_Str_17,
        .firstVariantId = DECOR_VARIANT_WOOD_SIGN_DEFAULT,
        .lastVariantId = DECOR_VARIANT_WOOD_SIGN_DEFAULT,
    },
    [DECOR_ID_FANCY_SIGN] =
    {
        .name = sText_Str_18,
        .firstVariantId = DECOR_VARIANT_FANCY_SIGN_DEFAULT,
        .lastVariantId = DECOR_VARIANT_FANCY_SIGN_DEFAULT,
    },
    [DECOR_ID_HORIZONTAL_FENCE] =
    {
        .name = sText_Str_19,
        .firstVariantId = DECOR_VARIANT_HORIZONTAL_FENCE_5X1,
        .lastVariantId = DECOR_VARIANT_HORIZONTAL_FENCE_2X1,
    },
    [DECOR_ID_VERTICAL_FENCE] =
    {
        .name = sText_Str_24,
        .firstVariantId = DECOR_VARIANT_VERTICAL_FENCE_LEFT_1X5,
        .lastVariantId = DECOR_VARIANT_VERTICAL_FENCE_RIGHT_1X2,
    },
    [DECOR_ID_RUG] =
    {
        .name = sText_Str_33,
        .firstVariantId = DECOR_VARIANT_RUG_FIRE_BLAST,
        .lastVariantId = DECOR_VARIANT_RUG_SPIKES,
    },
    [DECOR_ID_CHAIR] =
    {
        .name = sText_Str_41,
        .firstVariantId = DECOR_VARIANT_CHAIR_BRICK,
        .lastVariantId = DECOR_VARIANT_CHAIR_POKE_BALL,
    },
    [DECOR_ID_DESK] =
    {
        .name = sText_Str_51,
        .firstVariantId = DECOR_VARIANT_DESK_SMALL_WOODEN,
        .lastVariantId = DECOR_VARIANT_DESK_LARGE_LOG,
    },
    [DECOR_ID_PLANTS] =
    {
        .name = sText_Str_66,
        .firstVariantId = DECOR_VARIANT_PLANTS_RED,
        .lastVariantId = DECOR_VARIANT_PLANTS_GORGEOUS,
    },
    [DECOR_ID_FAUX_DOOR] =
    {
        .name = sText_Str_72,
        .firstVariantId = DECOR_VARIANT_FAUX_DOOR_DEFAULT,
        .lastVariantId = DECOR_VARIANT_FAUX_DOOR_DEFAULT,
    },
    [DECOR_ID_MUDBALL] =
    {
        .name = sText_Str_73,
        .firstVariantId = DECOR_VARIANT_MUDBALL_DEFAULT,
        .lastVariantId = DECOR_VARIANT_MUDBALL_DEFAULT,
    },
    [DECOR_ID_NOTE_PADS] =
    {
        .name = sText_Str_74,
        .firstVariantId = DECOR_VARIANT_NOTE_PADS_A,
        .lastVariantId = DECOR_VARIANT_NOTE_PADS_G,
    },
    [DECOR_ID_EFFECT_PADS] =
    {
        .name = sText_Str_82,
        .firstVariantId = DECOR_VARIANT_EFFECT_PADS_GLITTER,
        .lastVariantId = DECOR_VARIANT_EFFECT_PADS_SPIN,
    },
    [DECOR_ID_WATER_BALLOON] =
    {
        .name = sText_Str_86,
        .firstVariantId = DECOR_VARIANT_WATER_BALLOON_RED,
        .lastVariantId = DECOR_VARIANT_WATER_BALLOON_YELLOW,
    },
    [DECOR_ID_CLIMBING_FRAME] =
    {
        .name = sText_Str_89,
        .firstVariantId = DECOR_VARIANT_CLIMBING_FRAME_DEFAULT,
        .lastVariantId = DECOR_VARIANT_CLIMBING_FRAME_DEFAULT,
    },
    [DECOR_ID_SLIDE] =
    {
        .name = sText_Str_90,
        .firstVariantId = DECOR_VARIANT_SLIDE_DEFAULT,
        .lastVariantId = DECOR_VARIANT_SLIDE_DEFAULT,
    },
    [DECOR_ID_TENT] =
    {
        .name = sText_Str_91,
        .firstVariantId = DECOR_VARIANT_TENT_RED,
        .lastVariantId = DECOR_VARIANT_TENT_BLUE,
    },
    [DECOR_ID_SMALL_TV] =
    {
        .name = sText_Str_92,
        .firstVariantId = DECOR_VARIANT_SMALL_TV_STANDARD,
        .lastVariantId = DECOR_VARIANT_SMALL_TV_CUTE,
    },
    [DECOR_ID_LARGE_BRICK] =
    {
        .name = sText_Str_60,
        .firstVariantId = DECOR_VARIANT_LARGE_BRICK_RED,
        .lastVariantId = DECOR_VARIANT_LARGE_BRICK_YELLOW,
    },
    [DECOR_ID_LARGE_TIRE] =
    {
        .name = sText_Str_95,
        .firstVariantId = DECOR_VARIANT_LARGE_TIRE_DEFAULT,
        .lastVariantId = DECOR_VARIANT_LARGE_TIRE_DEFAULT,
    },
    [DECOR_ID_SMALL_FENCE] =
    {
        .name = sText_Str_96,
        .firstVariantId = DECOR_VARIANT_SMALL_FENCE_HORIZONTAL,
        .lastVariantId = DECOR_VARIANT_SMALL_FENCE_VERTICAL,
    },
    [DECOR_ID_STATUE] =
    {
        .name = sText_Str_99,
        .firstVariantId = DECOR_VARIANT_STATUE_DEFAULT,
        .lastVariantId = DECOR_VARIANT_STATUE_DEFAULT,
    },
    [DECOR_ID_QUEST_BOARD] =
    {
        .name = sText_Str_100,
        .firstVariantId = DECOR_VARIANT_QUEST_BOARD_DEFAULT,
        .lastVariantId = DECOR_VARIANT_QUEST_BOARD_DEFAULT,
    },
    [DECOR_ID_PC] =
    {
        .name = sText_Str_101,
        .firstVariantId = DECOR_VARIANT_PC_DEFAULT,
        .lastVariantId = DECOR_VARIANT_PC_DEFAULT,
    },
    [DECOR_ID_BED] =
    {
        .name = sText_Str_102,
        .firstVariantId = DECOR_VARIANT_BED_DEFAULT,
        .lastVariantId = DECOR_VARIANT_BED_DEFAULT,
    },
    [DECOR_ID_OUTFIT_CHANGING] =
    {
        .name = sText_Str_103,
        .firstVariantId = DECOR_VARIANT_OUTFIT_CHANGING_WARDROBE,
        .lastVariantId = DECOR_VARIANT_OUTFIT_CHANGING_DRAWERS,
    },
    [DECOR_ID_FLAG] =
    {
        .name = sText_Str_106,
        .firstVariantId = DECOR_VARIANT_FLAG_DEFAULT,
        .lastVariantId = DECOR_VARIANT_FLAG_DEFAULT,
    },
    [DECOR_ID_PC_WANDERING_PKMN] =
    {
        .name = sText_Str_107,
        .firstVariantId = DECOR_VARIANT_PC_WANDERING_PKMN_DEFAULT,
        .lastVariantId = DECOR_VARIANT_PC_WANDERING_PKMN_DEFAULT,
    },
    [DECOR_ID_APPLIANCES] =
    {
        .name = sText_Str_108,
        .firstVariantId = DECOR_VARIANT_APPLIANCES_FAN,
        .lastVariantId = DECOR_VARIANT_APPLIANCES_WASHING_MACHINE,
    },
    [DECOR_ID_CUSHIONS] =
    {
        .name = sText_Str_114,
        .firstVariantId = DECOR_VARIANT_CUSHIONS_POKE_BALL,
        .lastVariantId = DECOR_VARIANT_CUSHIONS_ZIGZAG,
    },
    [DECOR_ID_DOLL] =
    {
        .name = sText_Str_121,
        .firstVariantId = DECOR_VARIANT_DOLL_AZURILL,
        .lastVariantId = DECOR_VARIANT_DOLL_WYNAUT,
    },
    [DECOR_ID_REMOVE_DECOR] =
    {
        .name = sText_Str_161,
        .firstVariantId = DECOR_VARIANT_REMOVE_DECOR_DEFAULT,
        .lastVariantId = DECOR_VARIANT_REMOVE_DECOR_DEFAULT,
    },
};

