gItemDesc_EvolutionItem::
# 1 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Makes certain\n"
	.string "species of Pokémon\l"
	.string "evolve.$"

gItemDesc_QuestLog::
# 6 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A diary log for\n"
	.string "tracking Quests and\l"
	.string "Challenges.$"

gItemDesc_HealingFlask::
# 11 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Rechargable flask\n"
	.string "capable of healing\l"
	.string "all {PKMN} in the party.$"

gItemDesc_RidingWhistle::
# 16 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A whistle used to\n"
	.string "ride {PKMN} from the\l"
	.string "party.$"

gItemDesc_GoldRidingWhistle::
# 21 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A whistle used to\n"
	.string "ride registered {PKMN}.$"

gItemDesc_CGear::
# 26 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A watch which can\n"
	.string "remotely access the\l"
	.string "Config Lab.$"

gItemDesc_DaycarePhone::
# 31 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A Phone which can\n"
	.string "remotely access the\l"
	.string "Day Care.$"

gItemDesc_BuildingSupplies::
# 36 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Supplies used to\n"
	.string "create and upgrade\l"
	.string "buildings.$"

gItemDesc_TM::
# 41 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Reusable machine\n"
	.string "for teaching {PKMN} one\l"
	.string "specific move.$"

gItemDesc_TR::
# 46 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Single use machine\n"
	.string "for teaching {PKMN} one\l"
	.string "specific move.$"

gItemDesc_MaxMushroom::
# 51 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "When used on a {PKMN}\n"
	.string "they gain access\l"
	.string "their Gmax form.$"

gItemDesc_SmallCoinCase::
# 56 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Coin Case provides\n"
	.string "¥1000 on start of\l"
	.string "Adventure.$"

gItemDesc_LargeCoinCase::
# 61 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Coin Case provides\n"
	.string "¥10000 on start of\l"
	.string "Adventure.$"

gItemDesc_GoldenSeed::
# 66 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "todo - golden seed$"

gItemDesc_NormalPokeblock::
# 71 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Normal type {PKMN}.$"

gItemDesc_FightingPokeblock::
# 76 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Fighting type {PKMN}.$"

gItemDesc_FlyingPokeblock::
# 81 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Flying type {PKMN}.$"

gItemDesc_PoisonPokeblock::
# 86 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Poison type {PKMN}.$"

gItemDesc_GroundPokeblock::
# 91 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Ground type {PKMN}.$"

gItemDesc_RockPokeblock::
# 96 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Rock type {PKMN}.$"

gItemDesc_BugPokeblock::
# 101 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Bug type {PKMN}.$"

gItemDesc_GhostPokeblock::
# 106 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Ghost type {PKMN}.$"

gItemDesc_SteelPokeblock::
# 111 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Steel type {PKMN}.$"

gItemDesc_FirePokeblock::
# 116 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Fire type {PKMN}.$"

gItemDesc_WaterPokeblock::
# 121 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Water type {PKMN}.$"

gItemDesc_GrassPokeblock::
# 126 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Grass type {PKMN}.$"

gItemDesc_ElectricPokeblock::
# 131 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Electric type {PKMN}.$"

gItemDesc_PsychicPokeblock::
# 136 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Psychic type {PKMN}.$"

gItemDesc_IcePokeblock::
# 141 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Ice type {PKMN}.$"

gItemDesc_DragonPokeblock::
# 146 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Dragon type {PKMN}.$"

gItemDesc_DarkPokeblock::
# 151 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Dark type {PKMN}.$"

gItemDesc_FairyPokeblock::
# 156 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Fairy type {PKMN}.$"

gItemDesc_ShinyPokeblock::
# 161 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can be used on\n"
	.string "Routes to attract\l"
	.string "Shiny {PKMN}.$"

gItemDesc_StatPokeblock::
# 166 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "{POKEBLOCK} used to bake\n"
	.string "treats for {PKMN}.$"

gItemDesc_ShopPriceCharm::
# 172 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Shop prices are\n"
	.string "reduced by 50%$"

gItemDesc_ShopPriceCurse::
# 176 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Shop prices are\n"
	.string "increased by 40%$"

gItemDesc_FlinchCharm::
# 181 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly moves have\n"
	.string "a 15% chance to\l"
	.string "flinch.$"

gItemDesc_FlinchCurse::
# 185 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent moves\n"
	.string "have a 10% chance\l"
	.string "to flinch.$"

gItemDesc_CritCharm::
# 190 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly Pokémon\n"
	.string "have an increased\l"
	.string "crit rate.$"

gItemDesc_CritCurse::
# 194 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent Pokémon\n"
	.string "have an increased\l"
	.string "crit rate.$"

gItemDesc_ShedSkinCharm::
# 199 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly Pokémon\n"
	.string "have a 25% chance\l"
	.string "to cure status.$"

gItemDesc_ShedSkinCurse::
# 203 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent Pokémon\n"
	.string "have a 15% chance\l"
	.string "to cure status.$"

gItemDesc_WildIVCharm::
# 208 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Caught Pokémon are\n"
	.string "slightly stronger.$"

gItemDesc_WildIVCurse::
# 212 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Caught Pokémon are\n"
	.string "slightly weaker.$"

gItemDesc_CatchingCharm::
# 217 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Ball effectiveness\n"
	.string "is increased by\l"
	.string "200%.$"

gItemDesc_CatchingCurse::
# 221 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Ball effectiveness\n"
	.string "is decreased by 40%.$"

gItemDesc_GraceCharm::
# 226 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly moves have\n"
	.string "x1.75 to chance for\l"
	.string "effects.$"

gItemDesc_GraceCurse::
# 230 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent moves\n"
	.string "have x1.5 to chance\l"
	.string "for effects.$"

gItemDesc_WildCharm::
# 235 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Routes contain 2\n"
	.string "additional wild\l"
	.string "Pokémon.$"

gItemDesc_WildCurse::
# 239 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Routes contain 1\n"
	.string "less wild Pokémon.$"

gItemDesc_PriorityCharm::
# 244 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly moves have\n"
	.string "15% chance to apply\l"
	.string "Quick Claw.$"

gItemDesc_PriorityCurse::
# 248 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent moves\n"
	.string "have 10% chance to\l"
	.string "apply Quick Claw.$"

gItemDesc_EndureCharm::
# 253 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly Pokémon\n"
	.string "have a 40% chance\l"
	.string "to endure OHKOs.$"

gItemDesc_EndureCurse::
# 257 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent Pokémon\n"
	.string "have a 20% chance\l"
	.string "to endure OHKOs.$"

gItemDesc_TormentCharm::
# 262 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent {PKMN} cannot\n"
	.string "use the same move in\l"
	.string "a row.$"

gItemDesc_TormentCurse::
# 266 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly {PKMN} cannot\n"
	.string "use the same move in\l"
	.string "a row.$"

gItemDesc_PressureCharm::
# 271 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent Pokémon\n"
	.string "consume more PP per\l"
	.string "move.$"

gItemDesc_PressureCurse::
# 275 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly Pokémon\n"
	.string "consume more PP per\l"
	.string "move.$"

gItemDesc_UnawareCharm::
# 280 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly {PKMN} ignore\n"
	.string "Opponent {PKMN} {UP_ARROW}stat\l"
	.string "changes.$"

gItemDesc_UnawareCurse::
# 284 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent {PKMN} ignore\n"
	.string "Friendly {PKMN} {UP_ARROW}stat\l"
	.string "changes.$"

gItemDesc_AdaptabilityCharm::
# 289 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly Pokémon\n"
	.string "STAB increased by\l"
	.string "50%.$"

gItemDesc_AdaptabilityCurse::
# 293 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent Pokémon\n"
	.string "STAB increased by\l"
	.string "50%.$"

gItemDesc_ExtraLifeCharm::
# 298 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Permanent Sacred\n"
	.string "Ash effect.$"

gItemDesc_AllowSaveScumCharm::
# 302 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Allow regular Saving\n"
	.string "/ Reloading during\l"
	.string "Runs.$"

gItemDesc_PartyCurse::
# 307 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "The maximum number\n"
	.string "of Pokémon in your\l"
	.string "party is reduced.$"

gItemDesc_EverstoneCurse::
# 312 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "All regular\n"
	.string "Evolutions are\l"
	.string "disabled.$"

gItemDesc_BattleItemCurse::
# 317 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Items cannot be\n"
	.string "used in battle.\l"
	.string "(Except Poké Balls)$"

gItemDesc_SpeciesClauseCurse::
# 322 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Pokémon can't be\n"
	.string "caught if species\l"
	.string "already in party.$"

gItemDesc_ItemShuffleCurse::
# 327 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Entering a Battle\n"
	.string "will shuffle Held\l"
	.string "Items between {PKMN}.$"

gItemDesc_SnowballCurse::
# 332 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "For every badge, you\n"
	.string "gain an extra\l"
	.string "Random Curse.$"

gItemDesc_RandomanRouteSpawnCurse::
# 337 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Mr. Randoman will\n"
	.string "occasionally appear\l"
	.string "on routes.$"

gItemDesc_RandomanAlwaysSpawnCurse::
# 342 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Mr. Randoman will\n"
	.string "always appear when\l"
	.string "possible.$"

gItemDesc_AutoMoveSelectCurse::
# 347 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Opponent and\n"
	.string "Friendly {PKMN} pick\l"
	.string "moves at random.$"

gItemDesc_OneHitCurse::
# 352 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Friendly {PKMN} will\n"
	.string "faint in one hit in\l"
	.string "Trainer Battles.$"

gItemDesc_SnagCurse::
# 357 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Can only catch\n"
	.string "Trainer {PKMN} (After\l"
	.string "Trainer Battle).$"

gItemDesc_WildEggSpeciesCurse::
# 362 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Wild {PKMN} appear as\n"
	.string "their 1st evolution\l"
	.string "stage.$"

gHubAreaDesc_Todo::
# 371 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "todo - area desc$"

gHubAreaDesc_ChallengeFrontier::
# 376 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Access various new\n"
	.string "Quests and Items…$"

gHubAreaDesc_BerryField::
# 381 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Grow Berries and\n"
	.string "craft basic Potions.$"

gHubAreaDesc_Home::
# 386 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Personal area to\n"
	.string "Decorate & change\l"
	.string "Outfits.$"

gHubAreaDesc_Marts::
# 391 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Shops for TMs, Poké\n"
	.string "Balls, Held Items\l"
	.string "etc.$"

gHubAreaDesc_RideTraining::
# 396 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Train {PKMN} to help\n"
	.string "you in the\l"
	.string "Overworld.$"

gHubAreaDesc_DayCare::
# 401 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Bring extra {PKMN} into\n"
	.string "Adventures and\l"
	.string "hatch Eggs.$"

gHubAreaDesc_Market::
# 406 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Blend {POKEBLOCK} and\n"
	.string "improve {PKMN} IVs.$"

gHubUpgradeDesc_Home_LowerFloor::
# 411 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "An Interior space\n"
	.string "to decorate in the\l"
	.string "Home Base.$"

gHubUpgradeDesc_Home_UpperFloor::
# 416 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A 2nd floor with a\n"
	.string "bed allowing you to\l"
	.string "rest until a\l"
	.string "specific time.$"

gHubUpgradeDesc_Home_TownStyle::
# 421 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Change styles from\n"
	.string "Home Base e.g. Path$"

gHubUpgradeDesc_Home_BerryField1::
# 426 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A small plot to plant\n"
	.string "berries.$"

gHubUpgradeDesc_Home_BerryField2::
# 431 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A 2nd small plot to\n"
	.string "plant berries.\l"
	.string "(Unlocks Berry\l"
	.string "Fields area)$"

gHubUpgradeDesc_Home_GrassField::
# 436 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "A small cosmetic\n"
	.string "garden your caught\l"
	.string "{PKMN} can roam in.$"

gHubUpgradeDesc_Home_FieldShed::
# 441 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "TODO - Desc$"

gHubUpgradeDesc_Lab_UniqueMonSlots0::
# 446 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Increase number of\n"
	.string "Unique {PKMN} that can\l"
	.string "be tracked.$"

gHubUpgradeDesc_Lab_UniqueMonSlots1::
# 451 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Increase number of\n"
	.string "Unique {PKMN} that can\l"
	.string "be tracked.$"

gHubUpgradeDesc_Lab_UniqueMonRarity0::
# 456 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Allows Rare Unique\n"
	.string "{PKMN} to be tracked.\l"
	.string "(+Abilities)$"

gHubUpgradeDesc_Lab_UniqueMonRarity1::
# 461 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Allows Epic Unique\n"
	.string "{PKMN} to be tracked.\l"
	.string "(+Moves)$"

gHubUpgradeDesc_Lab_UniqueMonRarity2::
# 466 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Allows Exotic Unique\n"
	.string "{PKMN} to be tracked.\l"
	.string "(+Designed Sets)$"

gHubUpgradeDesc_Lab_UniqueMonRarity3::
# 471 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Allows Legendary\n"
	.string "Unique {PKMN} to be\l"
	.string "tracked.$"

gHubUpgradeDesc_AdventureEntrance_RandomStarter::
# 477 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Starter {PKMN} can be\n"
	.string "randomised when\l"
	.string "embarking on Runs.$"

gHubUpgradeDesc_AdventureEntrance_AdventureReplay::
# 482 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Adventures can be\n"
	.string "saved and replayed\l"
	.string "again.$"

gHubUpgradeDesc_BerryField_Brewing::
# 487 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Brew basic Potions\n"
	.string "from berries.$"

gHubUpgradeDesc_BerryField_ExtraField::
# 492 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "An additional plot\n"
	.string "to grown berries in.$"

gHubUpgradeDesc_BerryField_HigherYeild::
# 497 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Increase berries\n"
	.string "collected both in\l"
	.string "and out of\l"
	.string "Adventures.$"

gHubUpgradeDesc_Mart_GeneralStock::
# 502 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "General Shop has\n"
	.string "more items for sale.$"

gHubUpgradeDesc_Mart_PokeBalls::
# 507 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "An extra Shop which\n"
	.string "sells Poké Balls.$"

gHubUpgradeDesc_Mart_PokeBallsStock::
# 512 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Poké Ball Shop has\n"
	.string "more items for sale.$"

gHubUpgradeDesc_Mart_TMs::
# 517 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "An extra Shop which\n"
	.string "sells TMs.$"

gHubUpgradeDesc_Mart_TMsStock::
# 522 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "TM Shop has more\n"
	.string "items for sale.$"

gHubUpgradeDesc_Mart_TravelerBattleEnhancers::
# 527 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Battle Shop\n"
	.string "specializing in\l"
	.string "Battle Enhancers.$"

gHubUpgradeDesc_Mart_TravelerHeldItems::
# 532 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Battle Shop\n"
	.string "specializing in Held\l"
	.string "Items.$"

gHubUpgradeDesc_Mart_Bank::
# 537 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Increase starting\n"
	.string "money for\l"
	.string "Adventures.$"

gHubUpgradeDesc_TownSquare_TrainerSchool::
# 543 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Building for tips &\n"
	.string "tricks for\l"
	.string "Adventures.$"

gHubUpgradeDesc_TownSquare_MoveTutors::
# 548 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Tutor to teach or\n"
	.string "remove moves for\l"
	.string "{PKMN}.$"

gHubUpgradeDesc_DayCare_DayCareSlots::
# 554 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Adds an extra Day\n"
	.string "Care {PKMN} slot.$"

gHubUpgradeDesc_DayCare_Breeder::
# 559 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Use data from\n"
	.string "Pokédex to find {PKMN}\l"
	.string "Eggs.$"

gHubUpgradeDesc_DayCare_BreederSeenDex::
# 564 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Only need Seen\n"
	.string "Pokédex entry to\l"
	.string "find {PKMN} Eggs.$"

gHubUpgradeDesc_DayCare_Phone::
# 569 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Remotely access Day\n"
	.string "Care in and out of\l"
	.string "Adventures.$"

gHubUpgradeDesc_DayCare_Bakery::
# 574 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Bake {POKEBLOCK} into\n"
	.string "snacks used to\l"
	.string "improve IVs.$"

gHubUpgradeDesc_DayCare_PokeblockBlenders::
# 579 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Create more {POKEBLOCK}\n"
	.string "at once.$"

gHubUpgradeDesc_DayCare_TreatShop_Vanilla::
# 584 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Shop for {POKEBLOCK}.$"

gHubUpgradeDesc_DayCare_TreatShop::
# 589 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Shop for Mints to\n"
	.string "change {PKMN} natures.$"

gHubUpgradeDesc_DayCare_TreatShopStock::
# 594 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Treat Shop will now\n"
	.string "also sell {POKEBLOCK}.$"

gHubUpgradeDesc_DayCare_TeaShop::
# 599 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Tea used for\n"
	.string "changing the gender\l"
	.string "of {PKMN}.$"

gHubUpgradeDesc_DayCare_ExpShare0::
# 604 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Day Care {PKMN} gain\n"
	.string "25% of the {LV}s the\l"
	.string "Partner does.$"

gHubUpgradeDesc_DayCare_ExpShare1::
# 609 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Day Care {PKMN} gain\n"
	.string "50% of the {LV}s the\l"
	.string "Partner does.$"

gHubUpgradeDesc_DayCare_ExpShare2::
# 614 "data/scripts/Rogue/Strings/Rogue_Strings_Items.pory"
	.string "Day Care {PKMN} gain\n"
	.string "100% of the {LV}s the\l"
	.string "Partner does.$"
