gPlaceholder_Gym_PreBattleOpenning::
# 2 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "GYM\n"
	.string "TRAINER-STRING-PRE-BATTLE-OPENNING$"

gPlaceholder_Gym_PreBattleTaunt::
# 7 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "GYM TRAINER-STRING-PRE-BATTLE-TAUNT$"

gPlaceholder_Gym_PostBattleTaunt::
# 12 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "GYM\n"
	.string "TRAINER-STRING-POST-BATTLE-TAUNT$"

gPlaceholder_Gym_PostBattleCloser::
# 17 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "GYM\n"
	.string "TRAINER-STRING-POST-BATTLE-CLOSER$"

gPlaceholder_Trainer_PreBattleOpenning::
# 23 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "TRAINER-STRING-PRE-BATTLE-OPENNING$"

gPlaceholder_Trainer_PreBattleTaunt::
# 28 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "TRAINER-STRING-PRE-BATTLE-TAUNT$"

gPlaceholder_Trainer_PostBattleTaunt::
# 33 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "TRAINER-STRING-POST-BATTLE-TAUNT$"

gPlaceholder_Trainer_PostBattleCloser::
# 38 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "TRAINER-STRING-POST-BATTLE-CLOSER$"

gText_PokeblockHasNoEffect::
# 43 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "This {POKEBLOCK} has no effect.{PAUSE_UNTIL_PRESS}$"

gText_PokeblockWouldHaveNoEffect::
# 48 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "{POKEBLOCK} would have no effect, if scatted\n"
	.string "here.{PAUSE_UNTIL_PRESS}$"

gText_PokeblockWouldHaveNoEffectHoneyTree::
# 53 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "Only Typed {POKEBLOCK} can be scattered by\n"
	.string "Honey Trees.{PAUSE_UNTIL_PRESS}$"

gText_PokeblockAlreadyScattered::
# 58 "data/scripts/Rogue/Strings/Rogue_Strings_Common.pory"
	.string "{POKEBLOCK} has already been scattered\n"
	.string "here.{PAUSE_UNTIL_PRESS}$"
