name: CI

on:
  push:
    branches:
      - vanilla
      - vanilla-dev
      - expansion
      - expansion-dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    env:
      GAME_VERSION: EMERALD
      GAME_REVISION: 0
      GAME_LANGUAGE: ENGLISH
      MODERN: 0
      COMPARE: 0
      UNUSED_ERROR: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout agbcc
        uses: actions/checkout@v2
        with:
          path: agbcc
          repository: pret/agbcc

      - name: Install binutils
        run: |
          sudo apt update
          sudo apt install -y build-essential libpng-dev libelf-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP

      - name: Install Dependencies
        run: |
          ./init_deps.sh

      - name: Install agbcc
        run: |
          ./build.sh
          ./install.sh ../
        working-directory: agbcc

      #- name: Agbcc
      #  env:
      #    MODERN: 0
      #    COMPARE: 0
      #  run: make -j${nproc} -O all

      - name: Build Debug
        env:
          MODERN: 1
          COMPARE: 0
          RELEASE: 0
        run: make -j${nproc} -O all

      - name: Build Release
        env:
          MODERN: 1
          COMPARE: 0
          RELEASE: 1
        run: make -j${nproc} -O all

      - name: Update Memory Stats
        uses: actions/upload-artifact@v3
        with:
          name: Memory Stats
          path: pokeemerald_memorystats.csv

      - name: Test
        env:
          MODERN: 1
          TEST: 1
        run: |
          make -j${nproc} -O pokeemerald-test.elf
          make -j${nproc} check
